In [173]:
import pandas as pd
import math
import numpy as np

In [174]:
merged_data = pd.read_csv('merged_data.csv')

In [175]:
merged_data.head()

,listing_id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,comment_neg,comment_neu,comment_pos
0,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,NaN,f,2,0,2,0,1.85,0.011143,0.556818,0.424287
1,85156,https://www.airbnb.com/rooms/85156,20220911231053,2022-09-12,city scrape,Cosy Comfortable Irish Cottage 1 Double Bed,Our Cottage is a charming light filled cottage...,"I love Dundrum and its surrounding areas ,<br ...",https://a0.muscache.com/pictures/1749253/9ed2a...,193005,...,NaN,f,2,0,2,0,1.53,0.008495,0.548124,0.443367
2,159889,https://www.airbnb.com/rooms/159889,20220911231053,2022-09-12,city scrape,Friendly Single Room,Washing can be done at a cost of €5 per load....,Plenty of buses into the city and the area is ...,https://a0.muscache.com/pictures/3031697/a8259...,766611,...,NaN,f,3,0,3,0,2.78,0.012163,0.562225,0.422800
3,162809,https://www.airbnb.com/rooms/162809,20220911231053,2022-09-11,city scrape,5.5 miles south of Dublin City :^),A nice place to relax after the bustle of the ...,"Close to the sea, hill walks and the city - vi...",https://a0.muscache.com/pictures/86694529/c07b...,777681,...,NaN,f,2,0,2,0,3.68,0.013917,0.525071,0.461018
4,165828,https://www.airbnb.com/rooms/165828,20220911231053,2022-09-11,city scrape,Pádraig Pearse apt. Kilmainham,"Don't just visit Dublin, experience Dublin in ...","Enjoy a walk along the grand canal, or just ob...",https://a0.muscache.com/pictures/34311419/b3f6...,790601,...,NaN,t,5,5,0,0,0.48,0.017219,0.632781,0.349969

In [176]:
merged_data.columns

Index(['listing_id', 'listing_url', 'scrape_id', 'last_scraped', 'source',
       'name', 'description', 'neighborhood_overview', 'picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'comment_neg', 'comment_neu', 'comment_pos'],
      dtype='object')

# removing columns that i feel is not required based on intution -> IDs, empty columns etc. keeping only one neighbourhood column and dropping the rest

In [177]:
merged_data = merged_data.drop(columns=['scrape_id', 'neighbourhood_group_cleansed', 'bathrooms', 'calendar_updated', 'license', 'listing_url', 'last_scraped', 'source', 'host_id', 'host_url', 'host_location', 'host_neighbourhood', 'neighbourhood_cleansed'])

In [178]:
merged_data.columns

Index(['listing_id', 'name', 'description', 'neighborhood_overview',
       'picture_url', 'host_name', 'host_since', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'latitude', 'longitude', 'property_type', 'room_type',
       'accommodates', 'bathrooms_text', 'bedrooms', 'beds', 'amenities',
       'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm',
       'number_of_reviews_l30d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'comment_neg', 'comment_neu', 'comment_pos'],
      dtype='object')

In [179]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6209 entries, 0 to 6208
Data columns (total 65 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   listing_id                                    6209 non-null   int64
 1   name                                          6209 non-null   object
 2   description                                   6102 non-null   object
 3   neighborhood_overview                         3685 non-null   object
 4   picture_url                                   6209 non-null   object
 5   host_name                                     6209 non-null   object
 6   host_since                                    6209 non-null   object
 7   host_about                                    3082 non-null   object
 8   host_response_time                            3364 non-null   object
 9   host_response_rate                            3364 non-null   object
 10  host_acceptance_rate                          3605 non-null   object
 11  host_is_superhost                             6209 non-null   object
 12  host_thumbnail_url                            6209 non-null   object
 13  host_picture_url                              6209 non-null   object
 14  host_listings_count                           6209 non-null   int64
 15  host_total_listings_count                     6209 non-null   int64
 16  host_verifications                            6209 non-null   object
 17  host_has_profile_pic                          6209 non-null   object
 18  host_identity_verified                        6209 non-null   object
 19  neighbourhood                                 3685 non-null   object
 20  latitude                                      6209 non-null   float64
 21  longitude                                     6209 non-null   float64
 22  property_type                                 6209 non-null   object
 23  room_type                                     6209 non-null   object
 24  accommodates                                  6209 non-null   int64
 25  bathrooms_text                                6206 non-null   object
 26  bedrooms                                      6042 non-null   float64
 27  beds                                          6138 non-null   float64
 28  amenities                                     6209 non-null   object
 29  price                                         6209 non-null   object
 30  minimum_nights                                6209 non-null   int64
 31  maximum_nights                                6209 non-null   int64
 32  minimum_minimum_nights                        6209 non-null   int64
 33  maximum_minimum_nights                        6209 non-null   int64
 34  minimum_maximum_nights                        6209 non-null   int64
 35  maximum_maximum_nights                        6209 non-null   int64
 36  minimum_nights_avg_ntm                        6209 non-null   float64
 37  maximum_nights_avg_ntm                        6209 non-null   float64
 38  has_availability                              6209 non-null   object
 39  availability_30                               6209 non-null   int64
 40  availability_60                               6209 non-null   int64
 41  availability_90                               6209 non-null   int64
 42  availability_365                              6209 non-null   int64
 43  calendar_last_scraped                         6209 non-null   object
 44  number_of_reviews                             6209 non-null   int64
 45  number_of_reviews_ltm                         6209 non-null   int64
 46  number_of_reviews_l30d                        6209 non-null   int64
 47  first_review                                  6209 non-null   object
 48  last_review                                   6209 non-null   object
 49  review_scores_rating                          6209 non-null   float64
 50  review_scores_accuracy                        6085 non-null   float64
 51  review_scores_cleanliness                     6086 non-null   float64
 52  review_scores_checkin                         6081 non-null   float64
 53  review_scores_communication                   6085 non-null   float64
 54  review_scores_location                        6081 non-null   float64
 55  review_scores_value                           6079 non-null   float64
 56  instant_bookable                              6209 non-null   object
 57  calculated_host_listings_count                6209 non-null   int64
 58  calculated_host_listings_count_entire_homes   6209 non-null   int64
 59  calculated_host_listings_count_private_rooms  6209 non-null   int64
 60  calculated_host_listings_count_shared_rooms   6209 non-null   int64
 61  reviews_per_month                             6209 non-null   float64
 62  comment_neg                                   6209 non-null   float64
 63  comment_neu                                   6209 non-null   float64
 64  comment_pos                                   6209 non-null   float64
dtypes: float64(17), int64(21), object(27)
memory usage: 3.1+ MB

In [180]:
merged_data.isnull().sum()

listing_id                                        0
name                                              0
description                                     107
neighborhood_overview                          2524
picture_url                                       0
                                               ...
calculated_host_listings_count_shared_rooms       0
reviews_per_month                                 0
comment_neg                                       0
comment_neu                                       0
comment_pos                                       0
Length: 65, dtype: int64

# location using latitude and longitude

In [181]:
from geopy.geocoders import Nominatim

In [182]:
geolocator = Nominatim(user_agent="geoapiExercises")

In [183]:
merged_data['combined_location'] = merged_data["latitude"].astype(str) + "," + merged_data["longitude"].astype(str)

In [184]:
def get_location(location):
    lat, lng = location.split(',')
    loc = str(geolocator.geocode(str(lat)+","+str(lng)))
    loc = loc.replace('', '(')
    loc = loc.replace('', ')')
    return geolocator.geocode(str(lat)+","+str(lng))

In [185]:
merged_data['location_from_lat_lng'] = merged_data["combined_location"].apply(get_location)

In [186]:
# merged_data['location_from_lat_lng'] = merged_data['location_from_lat_lng'].astype(str)
# merged_data['location_from_lat_lng'] = merged_data['location_from_lat_lng'].replace('(', '')
# merged_data['location_from_lat_lng'] = merged_data['location_from_lat_lng'].replace(')', '')
merged_data['location_from_lat_lng'] = merged_data['location_from_lat_lng'].astype(str)
merged_data['location_from_lat_lng']

0       104, Beaumont Avenue, Churchtown Upper, Church...
1       26, Weston Road, Sweetmount, Churchtown Upper,...
2       56, Coolgariff Road, Beaumont, Artane H ED, Du...
3       5, Farmleigh Close, Stillorgan Park, Blackrock...
4       Tyrconnell Street, Inchicore, Ballyfermot F ED...
                              ...
6204    Presentation Primary School, Warrenmount, Blac...
6205    Ag Crú na Gréine, Wolfe Tone Street, North Cit...
6206    Kirwan Funeral Home, 21-23, Fairview Strand, M...
6207    125, North Circular Road, Cabra East C ED, Dub...
6208    Dal Riada, Portmarnock North ED, Fingal, Count...
Name: location_from_lat_lng, Length: 6209, dtype: object

In [187]:
merged_data = merged_data.drop(columns=["neighbourhood", "combined_location"])
merged_data

,listing_id,name,description,neighborhood_overview,picture_url,host_name,host_since,host_about,host_response_time,host_response_rate,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,comment_neg,comment_neu,comment_pos,location_from_lat_lng
0,44077,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,Teresa,2010-08-06,"I am a friendly outgoing Irishwoman ,who love...",within an hour,100%,...,f,2,0,2,0,1.85,0.011143,0.556818,0.424287,"104, Beaumont Avenue, Churchtown Upper, Church..."
1,85156,Cosy Comfortable Irish Cottage 1 Double Bed,Our Cottage is a charming light filled cottage...,"I love Dundrum and its surrounding areas ,<br ...",https://a0.muscache.com/pictures/1749253/9ed2a...,Teresa,2010-08-06,"I am a friendly outgoing Irishwoman ,who love...",within an hour,100%,...,f,2,0,2,0,1.53,0.008495,0.548124,0.443367,"26, Weston Road, Sweetmount, Churchtown Upper,..."
2,159889,Friendly Single Room,Washing can be done at a cost of €5 per load....,Plenty of buses into the city and the area is ...,https://a0.muscache.com/pictures/3031697/a8259...,Margaret,2011-07-01,Used to host students and now I am looking fo...,within an hour,100%,...,f,3,0,3,0,2.78,0.012163,0.562225,0.422800,"56, Coolgariff Road, Beaumont, Artane H ED, Du..."
3,162809,5.5 miles south of Dublin City :^),A nice place to relax after the bustle of the ...,"Close to the sea, hill walks and the city - vi...",https://a0.muscache.com/pictures/86694529/c07b...,Robbie,2011-07-04,I live here on the third floor of my house. Th...,within an hour,92%,...,f,2,0,2,0,3.68,0.013917,0.525071,0.461018,"5, Farmleigh Close, Stillorgan Park, Blackrock..."
4,165828,Pádraig Pearse apt. Kilmainham,"Don't just visit Dublin, experience Dublin in ...","Enjoy a walk along the grand canal, or just ob...",https://a0.muscache.com/pictures/34311419/b3f6...,Grainne,2011-07-07,"I'm Gráinne, originally from Co. Kildare and r...",within an hour,100%,...,t,5,5,0,0,0.48,0.017219,0.632781,0.349969,"Tyrconnell Street, Inchicore, Ballyfermot F ED..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6204,707685389742134998,Ensuite bedroom available in our newly built h...,Enjoy a lovely modern bedroom with an Ensuite ...,Dublin 8 (where our property is located) has b...,https://a0.muscache.com/pictures/miso/Hosting-...,Will,2013-10-30,"Love to travel, meet new people and see the wo...",within a few hours,100%,...,f,1,0,1,0,1.00,0.000000,0.302000,0.698000,"Presentation Primary School, Warrenmount, Blac..."
6205,707825078259308780,Bed in a mixed shared room (+3) - 1C1,Enjoy easy access to everything from this perf...,Capel 1,https://a0.muscache.com/pictures/miso/Hosting-...,Ana,2022-04-19,"“Hi there! My name is Ana, and I've been livin...",within an hour,98%,...,t,23,0,3,20,1.00,0.000000,0.591000,0.409000,"Ag Crú na Gréine, Wolfe Tone Street, North Cit..."
6206,708679904448712003,4-bedroom home a stones throw from Croke Park,Large 4 bedroom house located in a quiet cul-d...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,Sinéad,2016-08-04,NaN,within an hour,100%,...,f,1,1,0,0,1.00,0.000000,0.545000,0.455000,"Kirwan Funeral Home, 21-23, Fairview Strand, M..."
6207,709451504510289772,Period home with cosy double room,You will feel right at home in this stylish do...,The neighbourhood is safe and friendly. We are...,https://a0.muscache.com/pictures/22d7d5c5-bb02...,Geraldine,2014-09-09,"I am originally from Bristol, UK but have enjo...",within an hour,100%,...,t,1,0,1,0,1.00,0.000000,0.731000,0.269000,"125, North Circular Road, Cabra East C ED, Dub..."
6208,710054111904793673,Comfortable double bedroom in Portmarnock,We are delighted to offer a private room in ou...,Our house is located in the seaside town of Po...,https://a0.muscache.com/pictures/miso/Hosting-...,Noel,2022-09-06,NaN,NaN,NaN,...,f,1,0,1,0,1.00,0.000000,0.437000,0.563000,"Dal Riada, Portmarnock North ED, Fingal, Count..."

# remove location outside of Dublin

In [188]:
merged_data = merged_data[merged_data["location_from_lat_lng"].str.contains("Dublin") == True]

In [189]:
merged_data.location_from_lat_lng

0       104, Beaumont Avenue, Churchtown Upper, Church...
1       26, Weston Road, Sweetmount, Churchtown Upper,...
2       56, Coolgariff Road, Beaumont, Artane H ED, Du...
3       5, Farmleigh Close, Stillorgan Park, Blackrock...
4       Tyrconnell Street, Inchicore, Ballyfermot F ED...
                              ...
6204    Presentation Primary School, Warrenmount, Blac...
6205    Ag Crú na Gréine, Wolfe Tone Street, North Cit...
6206    Kirwan Funeral Home, 21-23, Fairview Strand, M...
6207    125, North Circular Road, Cabra East C ED, Dub...
6208    Dal Riada, Portmarnock North ED, Fingal, Count...
Name: location_from_lat_lng, Length: 6111, dtype: object

In [190]:
merged_data.isnull().sum()

listing_id                  0
name                        0
description               107
neighborhood_overview    2496
picture_url                 0
                         ...
reviews_per_month           0
comment_neg                 0
comment_neu                 0
comment_pos                 0
location_from_lat_lng       0
Length: 65, dtype: int64

# taking it out in csv to re-check data

In [191]:
# merged_data.to_csv('merged_data_updated.csv', index=False)

# Add missing values to the columns

In [192]:
merged_data["host_response_rate"] = merged_data["host_response_rate"].str.replace("%", "")
merged_data['host_response_rate'] = pd.to_numeric(merged_data['host_response_rate'], errors='coerce')
merged_data['host_response_rate']

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\585770439.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["host_response_rate"] = merged_data["host_response_rate"].str.replace("%", "")
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\585770439.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['host_response_rate'] = pd.to_numeric(merged_data['host_response_rate'], errors='coerce')

0       100.0
1       100.0
2       100.0
3        92.0
4       100.0
        ...
6204    100.0
6205     98.0
6206    100.0
6207    100.0
6208      NaN
Name: host_response_rate, Length: 6111, dtype: float64

In [193]:
merged_data.loc['host_response_rate'] = merged_data['host_response_rate'].fillna(0)

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\4212434132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data.loc['host_response_rate'] = merged_data['host_response_rate'].fillna(0)

In [194]:
merged_data['host_response_rate'] = merged_data['host_response_rate'].astype(float)

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\1994456878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['host_response_rate'] = merged_data['host_response_rate'].astype(float)

In [195]:
merged_data.loc['host_response_rate'] = merged_data['host_response_rate'].replace(0, math.floor(merged_data['host_response_rate'].mean()))

In [196]:
merged_data['host_response_rate'] = merged_data['host_response_rate'].fillna(math.floor(merged_data['host_response_rate'].mean()))

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\3318714245.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['host_response_rate'] = merged_data['host_response_rate'].fillna(math.floor(merged_data['host_response_rate'].mean()))

In [197]:
# merged_data.to_csv('merged_data_updated_1.csv', index=False)

# host acceptance rate

In [198]:
merged_data["host_acceptance_rate"] = merged_data["host_acceptance_rate"].str.replace("%", "")
merged_data['host_acceptance_rate'] = pd.to_numeric(merged_data['host_acceptance_rate'], errors='coerce')
merged_data.loc['host_acceptance_rate'] = merged_data['host_acceptance_rate'].fillna(0)
merged_data['host_acceptance_rate'] = merged_data['host_acceptance_rate'].astype(float)
merged_data.loc['host_acceptance_rate'] = merged_data['host_acceptance_rate'].replace(0, math.floor(merged_data['host_acceptance_rate'].mean()))
merged_data['host_acceptance_rate'] = merged_data['host_acceptance_rate'].fillna(math.floor(merged_data['host_acceptance_rate'].mean()))

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\311855069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["host_acceptance_rate"] = merged_data["host_acceptance_rate"].str.replace("%", "")
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\311855069.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['host_acceptance_rate'] = pd.to_numeric(merged_data['host_acceptance_rate'], errors='coerce')
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\311855069.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data.loc['host_acceptance_rate'] = merged_data['host_acceptance_rate'].fillna(0)
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\311855069.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['host_acceptance_rate'] = merged_data['host_acceptance_rate'].astype(float)
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\311855069.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['host_acceptance_rate'] = merged_data['host_acceptance_rate'].fillna(math.floor(merged_data['host_acceptance_rate'].mean()))

# FIlling host_response_time with most frequent

In [199]:
merged_data["host_response_time"]  = merged_data["host_response_time"].fillna(merged_data["host_response_time"].mode().iloc[0])
merged_data["host_about"]  = merged_data["host_about"].fillna(merged_data["host_about"].mode().iloc[0])

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\174087772.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["host_response_time"]  = merged_data["host_response_time"].fillna(merged_data["host_response_time"].mode().iloc[0])
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\174087772.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["host_about"]  = merged_data["host_about"].fillna(merged_data["host_about"].mode().iloc[0])

In [200]:
merged_data["host_response_time"].isnull().sum()

0

In [201]:
merged_data["bedrooms"].mean()

1.5165629729275265

# filling all other missing values and dropping empty columns

In [202]:
#convert description to present or not present as the exact details does not matter
# merged_data['description'] = np.where(merged_data['description'].isnull(), 0, 1)
merged_data['neighborhood_overview'] = np.where(merged_data['neighborhood_overview'].isnull(), 0, 1)

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\999328701.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['neighborhood_overview'] = np.where(merged_data['neighborhood_overview'].isnull(), 0, 1)

In [203]:
merged_data["bedrooms"]  = merged_data["bedrooms"].fillna(math.floor(merged_data["bedrooms"].mean()))
merged_data["beds"]  = merged_data["beds"].fillna(math.floor(merged_data["beds"].mean()))
merged_data["bathrooms_text"]  = merged_data["bathrooms_text"].fillna(merged_data["bathrooms_text"].mode().iloc[0])
merged_data["review_scores_accuracy"]  = merged_data["review_scores_accuracy"].fillna(round(merged_data["review_scores_accuracy"].mean(), 2))
merged_data["review_scores_cleanliness"]  = merged_data["review_scores_cleanliness"].fillna(round(merged_data["review_scores_cleanliness"].mean(), 2))
merged_data["review_scores_value"]  = merged_data["review_scores_value"].fillna(round(merged_data["review_scores_value"].mean(), 2))
merged_data["review_scores_communication"]  = merged_data["review_scores_communication"].fillna(round(merged_data["review_scores_communication"].mean(), 2))
merged_data["review_scores_location"]  = merged_data["review_scores_location"].fillna(round(merged_data["review_scores_location"].mean(), 2))
merged_data["review_scores_checkin"]  = merged_data["review_scores_checkin"].fillna(round(merged_data["review_scores_checkin"].mean(), 2))

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["bedrooms"]  = merged_data["bedrooms"].fillna(math.floor(merged_data["bedrooms"].mean()))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["beds"]  = merged_data["beds"].fillna(math.floor(merged_data["beds"].mean()))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["bathrooms_text"]  = merged_data["bathrooms_text"].fillna(merged_data["bathrooms_text"].mode().iloc[0])
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["review_scores_accuracy"]  = merged_data["review_scores_accuracy"].fillna(round(merged_data["review_scores_accuracy"].mean(), 2))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["review_scores_cleanliness"]  = merged_data["review_scores_cleanliness"].fillna(round(merged_data["review_scores_cleanliness"].mean(), 2))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["review_scores_value"]  = merged_data["review_scores_value"].fillna(round(merged_data["review_scores_value"].mean(), 2))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["review_scores_communication"]  = merged_data["review_scores_communication"].fillna(round(merged_data["review_scores_communication"].mean(), 2))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["review_scores_location"]  = merged_data["review_scores_location"].fillna(round(merged_data["review_scores_location"].mean(), 2))
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2948351633.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data["review_scores_checkin"]  = merged_data["review_scores_checkin"].fillna(round(merged_data["review_scores_checkin"].mean(), 2))

In [204]:
merged_data = merged_data.drop(labels=['host_response_rate','host_acceptance_rate'], axis=0)

# replacing string value of the column to present or not present ex: name does not matter if name is given or not that matters

In [205]:
merged_data['name'] = np.where(merged_data['name'].isnull(), 0, 1)
merged_data['host_name'] = np.where(merged_data['host_name'].isnull(), 0, 1)
merged_data['host_is_superhost'] = np.where(merged_data['host_is_superhost'] == 'f', 0, 1)
merged_data['host_has_profile_pic'] = np.where(merged_data['host_has_profile_pic'] == 'f', 0, 1)
merged_data['host_identity_verified'] = np.where(merged_data['host_identity_verified'] == 'f', 0, 1)
merged_data['has_availability'] = np.where(merged_data['has_availability'] == 'f', 0, 1)
merged_data['instant_bookable'] = np.where(merged_data['instant_bookable'] == 'f', 0, 1)

# converting certain columns to available or not available

In [206]:
merged_data['picture_url'] = np.where(merged_data['picture_url'].isnull(), 0, 1)
merged_data['host_thumbnail_url'] = np.where(merged_data['host_thumbnail_url'].isnull(), 0, 1)
merged_data['host_picture_url'] = np.where(merged_data['host_picture_url'].isnull(), 0, 1)
#add for description

In [207]:
merged_data['description'] = merged_data['description'].astype(str)

# adding sentiment analysis on host about and using it

In [208]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [209]:
# merged_data['compound'] = [analyzer.polarity_scores(x)['compound'] for x in review_df['comments']]
merged_data['host_about_neg'] = [analyzer.polarity_scores(x)['neg'] for x in merged_data['host_about']]
merged_data['host_about_neu'] = [analyzer.polarity_scores(x)['neu'] for x in merged_data['host_about']]
merged_data['host_about_pos'] = [analyzer.polarity_scores(x)['pos'] for x in merged_data['host_about']]

In [210]:
merged_data['description_about_neg'] = [analyzer.polarity_scores(x)['neg'] for x in merged_data['description']]
merged_data['description_about_neu'] = [analyzer.polarity_scores(x)['neu'] for x in merged_data['description']]
merged_data['description_about_pos'] = [analyzer.polarity_scores(x)['pos'] for x in merged_data['description']]

In [211]:
merged_data = merged_data.drop(columns=['host_about', 'description'])

# divide host _verifications  as done for ammenities

In [212]:
merged_data['host_verifications'] = merged_data['host_verifications'].astype(str)
merged_data.host_verifications = merged_data.host_verifications.str.replace(r"{[|]}|\"","").str.strip().str.split(",")
host_verifications_df = pd.DataFrame([vrf for vrf in merged_data.host_verifications.apply(lambda item: dict(map(lambda vrf: (vrf,1),item))).values]).fillna(0)

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2725304755.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  merged_data.host_verifications = merged_data.host_verifications.str.replace(r"{[|]}|\"","").str.strip().str.split(",")

In [213]:
host_verifications_df.columns = host_verifications_df.columns.str.replace('[', '')
host_verifications_df.columns = host_verifications_df.columns.str.replace(']', '')
host_verifications_df.columns = host_verifications_df.columns.str.replace('\\', '__')
host_verifications_df.columns = host_verifications_df.columns.str.replace('__u', '')
host_verifications_df.columns = host_verifications_df.columns.str.replace('\'', '')
host_verifications_df.columns = host_verifications_df.columns.str.replace(' ', '')
host_verifications_df

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\1794984757.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  host_verifications_df.columns = host_verifications_df.columns.str.replace('[', '')
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\1794984757.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  host_verifications_df.columns = host_verifications_df.columns.str.replace(']', '')
C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\1794984757.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  host_verifications_df.columns = host_verifications_df.columns.str.replace('\\', '__')

      email  phone  phone  work_email  phone  phone       email
0       1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
1       1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
2       1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
3       1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
4       1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
...     ...    ...    ...         ...    ...    ...  ...    ...
6106    1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
6107    1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
6108    1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
6109    1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0
6110    1.0    1.0    0.0         0.0    0.0    0.0  0.0    0.0

[6111 rows x 8 columns]

In [214]:
host_verifications_df = host_verifications_df.groupby(host_verifications_df.columns, axis=1).agg(np.max)
host_verifications_df = host_verifications_df.drop(host_verifications_df.columns[0], axis=1)
host_verifications_df

      email  phone  work_email
0       1.0    1.0         0.0
1       1.0    1.0         0.0
2       1.0    1.0         0.0
3       1.0    1.0         0.0
4       1.0    1.0         0.0
...     ...    ...         ...
6106    1.0    1.0         0.0
6107    1.0    1.0         0.0
6108    1.0    1.0         0.0
6109    1.0    1.0         0.0
6110    1.0    1.0         0.0

[6111 rows x 3 columns]

In [215]:
merged_data = merged_data.join(host_verifications_df)

In [216]:
merged_data = merged_data.drop(columns=["host_verifications"])

In [217]:
merged_data['email'] = merged_data['email'].fillna(0)
merged_data['phone'] = merged_data['phone'].fillna(0)
merged_data['work_email'] = merged_data['work_email'].fillna(0)

In [218]:
merged_data.shape

(6111, 71)

# Dropping date columns

In [219]:
merged_data = merged_data.drop(columns=["host_since", "calendar_last_scraped", "first_review", "last_review"])

# using one hot encoding for required columns

In [220]:
encoded_data = pd.get_dummies(merged_data[["host_response_time", "location_from_lat_lng", "property_type", "room_type", "bathrooms_text"]])
encoded_data.columns = encoded_data.columns.str.replace(' ', '')
encoded_data = encoded_data.loc[:,~encoded_data.columns.duplicated()].copy()
encoded_data

,host_response_time_afewdaysormore,host_response_time_withinaday,host_response_time_withinafewhours,host_response_time_withinanhour,"location_from_lat_lng_#148MobhiRoad,BotanicRoad,SaintMobhiRoad,Drumcondra,BotanicAED,Dublin,CountyDublin,Leinster,D09CF72,Éire/Ireland","location_from_lat_lng_#200ProspectWay,ProspectAvenue,ProspectWay,GlasnevinAED,Dublin,CountyDublin,Leinster,D09W0X9,Éire/Ireland","location_from_lat_lng_#205SwordsRoad,IveraghRoad,SwordsRoad,Whitehall,DrumcondraNorthCED,Dublin,CountyDublin,Leinster,D09RDT8,Éire/Ireland","location_from_lat_lng_#22HomeFarmRoad,DrumcondraRoad,HomeFarmRoad,DrumcondraSouthCED,Dublin,CountyDublin,Leinster,D09T6P7,Éire/Ireland","location_from_lat_lng_#2819DundrumRoad,BirdAvenue,DundrumRoad,WindyArbour,Farranboley,Clonskeagh-MilltownED,Dundrum,DúnLaoghaire-Rathdown,CountyDublin,Leinster,D14V3K8,Éire/Ireland","location_from_lat_lng_#2841SandyfordRd,DundrumTownCentre,SandyfordRoad,Dundrum,Dundrum-SandyfordED,Dundrum,DúnLaoghaire-Rathdown,CountyDublin,Leinster,D16VK54,Éire/Ireland",...,bathrooms_text_6baths,bathrooms_text_6sharedbaths,bathrooms_text_7baths,bathrooms_text_7.5baths,bathrooms_text_8baths,bathrooms_text_8.5baths,bathrooms_text_9.5baths,bathrooms_text_Half-bath,bathrooms_text_Privatehalf-bath,bathrooms_text_Sharedhalf-bath
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6204,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6205,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6206,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6207,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6208,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [221]:
merged_data = merged_data.drop(columns=["host_response_time", "location_from_lat_lng", "property_type", "room_type", "bathrooms_text", "listing_id"])
merged_data = merged_data.join(encoded_data)

# price column update

In [222]:
merged_data['price'] = merged_data['price'].str.replace("$", "")
merged_data['price'] = merged_data['price'].str.replace(",", "")

C:\Users\amogh\AppData\Local\Temp\ipykernel_27048\2793720395.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  merged_data['price'] = merged_data['price'].str.replace("$", "")

In [223]:
merged_data['price'] = merged_data['price'].astype(float)

In [224]:
merged_data.to_csv('merged_data_updated.csv', index=False)

In [225]:
merged_data

,listing_id,name,neighborhood_overview,picture_url,host_name,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,...,bathrooms_text_6baths,bathrooms_text_6sharedbaths,bathrooms_text_7baths,bathrooms_text_7.5baths,bathrooms_text_8baths,bathrooms_text_8.5baths,bathrooms_text_9.5baths,bathrooms_text_Half-bath,bathrooms_text_Privatehalf-bath,bathrooms_text_Sharedhalf-bath
0,4.407700e+04,1,1,1,1,100.0,99.0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,8.515600e+04,1,1,1,1,100.0,99.0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1.598890e+05,1,1,1,1,100.0,95.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1.628090e+05,1,1,1,1,92.0,87.0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1.658280e+05,1,1,1,1,100.0,91.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6204,7.076854e+17,1,1,1,1,100.0,100.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
6205,7.078251e+17,1,1,1,1,98.0,100.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
6206,7.086799e+17,1,0,1,1,100.0,100.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
6207,7.094515e+17,1,1,1,1,100.0,100.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
6208,7.100541e+17,1,1,1,1,95.0,100.0,0,1,1,...,0,0,0,0,0,0,0,0,0,0